### ISSUE TITLE
Coding error

### ISSUE THREAD

**Issue by Agent-Isai** [irc-CoBot/pyCoBot#12]
While trying to launch the bot I got:

Isai@vps7.VPS.NYC.agentisai.net:~/CoBot$ python3 pyCoBot.py
Python3 is starting up... Error!
Traceback (most recent call last):
  File "pycobot.py", line 7, in <module>
    from pycobot.pycobot import pyCoBot
  File "/home/Isai/CoBot/pycobot/pycobot.py", line 42, in <module>
    print("Al parecer no hay ning\xfan usuario!")
UnicodeEncodeError: 'ascii' codec can't encode character '\xfa' in position 22: ordinal not in range(128)
Cannot parse, aborting...
[1].                     Stopped.
Isai@vps7.VPS.NYC.agentisai.net:~/CoBot$

**Comment by Polsaker** [comment]
The encoding is declared on that file and there's no file named pyCoBot.py (with the cases). Did you modify the bot?

**Comment by Agent-Isai** [comment]
No

**Comment by JeDa** [comment]
Actually it is weird. It should work. For some reason works on English VPSs that spanish stuff. Try reinstalling Python3. For example, in Debian/Ubuntu:
apt-get install --reinstall python3
